// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBciXF2jei2SqTGa-EUaatIdHTXD_ZwIlo',
    appId: '1:922872911350:web:58a6fa23870df3acb223d7',
    messagingSenderId: '922872911350',
    projectId: 'whatsapp-3720a',
    authDomain: 'whatsapp-3720a.firebaseapp.com',
    storageBucket: 'whatsapp-3720a.appspot.com',
    measurementId: 'G-5W8QWKBN42',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGmVy65oWQUw_DFPQGSagjcAb3rN4aL5M',
    appId: '1:922872911350:android:27d7092dc85ad498b223d7',
    messagingSenderId: '922872911350',
    projectId: 'whatsapp-3720a',
    storageBucket: 'whatsapp-3720a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPJERuOMTGGsDK_xQNP5cVwtp0FZP8Yck',
    appId: '1:922872911350:ios:812f8a3b0a6757dfb223d7',
    messagingSenderId: '922872911350',
    projectId: 'whatsapp-3720a',
    storageBucket: 'whatsapp-3720a.appspot.com',
    iosBundleId: 'com.example.whatsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPJERuOMTGGsDK_xQNP5cVwtp0FZP8Yck',
    appId: '1:922872911350:ios:075aa0a474308ed5b223d7',
    messagingSenderId: '922872911350',
    projectId: 'whatsapp-3720a',
    storageBucket: 'whatsapp-3720a.appspot.com',
    iosBundleId: 'com.example.whatsapp.RunnerTests',
  );
}
